version: '3.9'

services:
  agence_api:
    build: .
    image: agence-api:latest
    container_name: agence_api
    stdin_open: true
    tty: true
    working_dir: /var/www/
    ports:
      - 81:80
      - 8000:8000
    volumes:
      - ./:/var/www
    networks:
      - agence-network

  agence_db:
    image: mysql:latest
    container_name: agence_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - agence-network

networks:
  agence-network:
    driver: bridge
